from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .native_nodes import NODE_CLASS_MAPPINGS as NATIVE_NODE_CLASS_MAPPINGS
from .native_nodes import NODE_DISPLAY_NAME_MAPPINGS as NATIVE_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS.update(NATIVE_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(NATIVE_NODE_DISPLAY_NAME_MAPPINGS)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
